services:
  mysql:
    image: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 126
    volumes:
      - meubanco:/var
    networks:
      minharede:
        ipv4_address: 192.168.1.2

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 0.0.0.0:8000:80
    volumes:
      - meubanco:/etc/phpmyadmin
    networks:
      minharede:
    environment:
      PMA_HOST: 192.168.1.2

volumes:
  meubanco:

networks:
  minharede:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.1/24
